### ISSUE TITLE
MS.SHAREPOINT.4.2v1 functional test fails in SPO mode for GCC high test tenant

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#1060]
# 🐛 Summary #

The functional testplan for SharePoint fails when running against the GCC high G5 test tenant due to the Set-SPOSite command option `-DenyAddAndCustomizePages` flag which is not supported for the "MySite" host.  Issue seems to be that the test assumes this property can be set on the first site in the tenant site list, but that is not true for this tenant.

## To reproduce ##

1. Setup SharePoint functional testing against the GCC high G5 test tenant
2. Set testing filter to MS.SHAREPOINT.4.2*
3. Review the value of the first site in the `Get-SPOSite` list of URLs showing the URL of the site at the 0 index

## Expected behavior ##

Expected the MS.SHAREPOINT.4.2v1 compliant and non-compliant test cases to pass.

## Any helpful log output or screenshots ##

Screenshot showing failure in GCC high test tenant
![Screenshot 2024-04-04 at 1 56 41 PM](https://github.com/cisagov/ScubaGear/assets/108814318/e76cf562-919e-46b6-b989-e4399cf6505a)

**Comment by tkol2022** [comment]
I believe this is the same issue that Crutch previously posted about: #622 

- I am not sure that we can hard code the index to [1]. If I remember correctly, we need to get the configuration information for the top level Sharepoint site which follows the convention https://**tenantName-admin**.sharepoint.com. We cannot assume any order in the sites listed by Get-SPOSite.
- Below is some code that we can use for the functional test based on what Crutch recommended and it worked for me. The part that is different from the existing functional test is the tailored Get-SPOSite command to get the top level site.

```
$Site=[System.Uri]((Get-SPOSite -Limit All | Where-Object {($_.Url -NotLike '*-my*') -And ($_.Url -Like '*/') }).Url);Set-SPOSite -Identity "$($Site.Scheme)://$($Site.Authority)" -DenyAddAndCustomizePages:$false
```

- Although we can fix the functional test case now, we should discuss the long-term impacts of Microsoft's changes to custom script settings 4.2 and 4.1 with @ahuynhMITRE via #977 so that we know how to modify Scuba + ScubaGear if needed.
