### ISSUE TITLE
MS.AAD.6.1 Does not account for federated domains

### ISSUE THREAD

**Issue by Jeff-Jerousek** [cisagov/ScubaGear#1080]
# 🐛 Summary #

What's wrong? Please be specific.
Any federated domains do not have the fields:
 passwordNotificationWindowInDays
 passwordValidityPeriodInDays

**Note for whoever gets assigned this issue**: refer to the [instructions in this comment](https://github.com/cisagov/ScubaGear/issues/1080#issuecomment-2086346747) for the code changes needed.

## To reproduce ##

Run Get-MgBetaDomain against a tenant with federated domains (ADFS).

## Expected behavior ##

The password policy is enforced locally, an exception for any federated domains would do the trick.

## Any helpful log output or screenshots ##

Paste the results here:

```console

{
  "id": "generic.domain.com",
  "authenticationType": "Federated",
  "isAdminManaged": true,
  "isDefault": false,
  "isInitial": false,
  "isRoot": false,
  "isVerified": true,
  "supportedServices": [ "Email", "OfficeCommunicationsOnline", "OrgIdAuthentication", "Intune" ]
}

```

Add any screenshots of the problem here.

**Comment by tkol2022** [comment]
@Jeff-Jerousek This is an excellent find. Thank you for raising it to our attention. I verified what you are saying and I am thinking to fix this we can add another filter to our Rego code that will only evaluate domains with AuthenticationType = Managed and thus ignore domains that have the type Federated. One of our test tenants has a federated domain and the code incorrectly picked up that domain as being non compliant with 6.1 (screenshots below).

![image](https://github.com/cisagov/ScubaGear/assets/107076927/bcd3a460-127b-4227-8049-56a9b3d6c0d1)
![image](https://github.com/cisagov/ScubaGear/assets/107076927/2a97da31-12dc-42b5-a565-4e74eefba602)

Thoughts?

@gdasher would like your opinion as well?

**Comment by Jeff-Jerousek** [comment]
Didn't mean to close, just hit enter.

**Comment by gdasher** [comment]
I think the proposal is reasonable for changing the tool.  I wouldn't change the normative policy requirement but we can offer some color like we do on MFA that it can be implemented the IDP in a federated context.

Aside: I think a similar situation happens with MFA, where an organization could enforce MFA in their IDP (whether ADFS via smart cards and UBE or some other IDP solution that has MFA support).  We should take offline whether we want to update the tool for that case as well--the baseline already refers to federated domains explicitly but I don't think the tool does anything differently in that case. I am more torn on MFA than passwords because the situation is more complex (e.g. the CAP policy can be satisfied in some cases by MFA claims, but not at the granularity of "phishing resistant").  But for this issue I think the proposal makes sense.

**Comment by mitchelbaker-cisa** [comment]
After adjusting MS.AAD.6.1 to account for federated domains, I wanted to test for the situation where all domains returned from `Get-MgBetaDomain` have AuthenticationType = Federated. Something along the lines of: 

```
[
  {
    "id": "generic.domain1.com",
    "authenticationType": "Federated",
    "isVerified": true,
  },
  {
    "id": "generic.domain2.com",
    "authenticationType": "Federated",
    "isVerified": true,
  },
  ...
]
```

However, an onmicrosoft.com fallback domain is provided by default when first signing up for M365, https://learn.microsoft.com/en-us/microsoft-365/admin/setup/add-or-replace-your-onmicrosoftcom-domain?view=o365-worldwide. The article also states that once added an onmicrosoft.com domain cannot be removed, which defeats the purpose of the above test case. @gdasher Can you confirm if tenants must have at least one managed domain?
