### ISSUE TITLE
Fix the OPA version bump workflow to work with the new README

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#1187]
# 🐛 Summary #

The OPA version bump workflow used to regularly bump the OPA version is currently erroring out do to the README changes.
This issue 

## To reproduce ##

View the errors in the latest OPA version bump workflows.
## Expected behavior ##

For the workflows to bump the versions without any errors.

**Comment by james-garriss** [comment]
I think the real solution to this sort of problem is related to the "we don't have all of our static requirements in one constants/config file" problem that other issues have brought up.  IOW, this isn't a uniquely OPA problem.  The README also talks about the names/versions of the PS modules that are installed.  We should solve the problem one time, one way for everything, instead of piece-mealing it.
