### ISSUE TITLE
Get-PrivilegedUser fails when a Privileged Entra Id role is assigned to a group

### ISSUE THREAD

**Issue by thetolkienblackguy** [cisagov/ScubaGear#1288]
# 🐛 Summary #

If you have assigned roles to groups as opposed to users the assessment fails to perform MS.AAD.7.1v1, MS.AAD.7.1v2, and MS.AAD.7.1v3 and returns in error response. The function Get-PrivilegedUsers terminates with a "Request_ResourceNotFound" error

## To reproduce ##

1. Assign a privileged role to a group in Entra Id
2. Run  `Invoke-SCuBA -ProductNames aad -M365Environment gcc`

## Expected behavior ##

The function Get-PrivilegedUsers should be able to detect that a group and not a user has been assigned a role and then recursively identify the users within the group.

## Any helpful log output or screenshots ##

```console
WARNING: Error running Get-PrivilegedUser. Resource '00000000-0000-0000-0000-00000000' does not exist or one of its  queried reference-property objects are not present.                                                                                                                                                                                            Status: 404 (NotFound)                                                                                                  ErrorCode: Request_ResourceNotFound                                                                                     Date: 2024-08-26T20:43:17                                                                                               
Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 567553e9-3fef-4e1a-9137-1cca64354c8c
client-request-id             : 313d9ff2-90fe-4cda-83f5-f38e21a4ba94
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"East
US","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"BL6PEPF0001F5EF"}}
Link                          :
<https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:copilotExportAPI&from=2024-07-01
&to=2024-08-01>;rel="deprecation";type="text/html",<https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=b
eta,PrivatePreview:cloudLicensing&from=2024-04-01&to=2024-05-01>;rel="deprecation";type="text/html",<https://developer.
microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:cloudLicensing&from=2024-04-01&to=2024-05-01>;rel="
deprecation";type="text/html",<https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,Users&from=2022-0
2-01&to=2022-03-01>;rel="deprecation";type="text/html"
Deprecation                   : Thu, 17 Feb 2022 23:59:59 GMT
Sunset                        : Sat, 17 Feb 2024 23:59:59 GMT
x-ms-resource-unit            : 1
Cache-Control                 : no-cache
Date                          : Mon, 26 Aug 2024 20:43:16 GMT
```

## Suggestion
It appears you're trying to catch the exception when executing Get-MgBetaUser within the function.  It may be more beneficial to first run `Get-MgDirectoryObject -DirectoryObjectId $User.Id` to retrieve the object then use the @odata.type to determine if the principal is a user or group, then build if\else logic to either get the data you need from the user object or return the members of the group.  This is probably cleaner regardless of the underlying bug.

**Comment by tkol2022** [comment]
Hello @thetolkienblackguy,
Thank you for reporting the issue. In general, the tool supports when roles are assigned to a group. Also thank you for your sample code suggestion - we will review it for a potential improvement to the tool!

The error 404 Request_ResourceNotFound has been known to occur in Get-PrivilegedUser when a user has been deleted in the tenant and ScubaGear is run after the deletion. In certain circumstances, even though the user is no longer in the tenant, there are some phantom role or group assignments that stick around in the directory and when ScubaGear runs it tries to query for the phantom user and hence we see the 404 error.

Can you please provide this information which will help us precisely diagnose the problem you are observing and work on a fix?

- Did you or any of your team delete users recently in the tenant? Specifically users that would be assigned to a role or group that is assigned to one of the [8 roles that ScubaGear processes](https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/baselines/aad.md#highly-privileged-roles).
- Are you using PIM groups, or just regular Entra Id groups?
- Do you assign the role to the group as Active or Eligible?
- If we develop a fix in the coming weeks, would you be able to help us alpha test it? This is assuming the error still occurs in your environment when the fix is available.

I was able to re-create the error in my environment but I don't know if your situation is exactly the same. Nonetheless I am sharing with the hopes that it will help you get past the error and at the bottom of this comment I have a potential workaround.

1. I created a synthentic user named "deletemeprivuser2"
2. I created a group in Entra Id PIM named "Ted's PIM Group 2"
3. I assigned the user to the PIM Group in the PIM portal as a Member and as Eligible
4. I assigned the group "Ted's PIM Group 2" to the Sharepoint Administrator role as Active
5. I delete the user "deletemeprivuser2"

![image](https://github.com/user-attachments/assets/97cbb7e3-98ce-45a6-bd7c-ad1ade6da91a)
![image](https://github.com/user-attachments/assets/46e3525d-aa81-4c4d-b18d-8b11e25ff9aa)

Once the user was deleted, I observed a phantom resource in the PIM for Groups portal. When I open the Eligible assignments for the "Ted's PIM Group 2", the user "deletemeprivuser2" is still there, despite the fact that I deleted that user. I created that user around 1:44PM and it is now 3:25 PM and the phantom resource is still there, which indicates that these phantom resources can last for hours. I will check again tomorrow to see if it is still there.

This triggers ScubaGear to produce the error:

![image](https://github.com/user-attachments/assets/f8e2361d-c25b-4c1c-a5c9-b85e57caf9cf)

![image](https://github.com/user-attachments/assets/a0d2eb1d-9bdc-4017-b890-d91f9eed64e4)

## Potential Workaround

- Run ScubaGear again and see if it still errors out. The phantom resource may have been deleted. No guarantee.
- If it still errors out, then you might see if you can locate the phantom resource (i.e. which user or group was deleted). If the user was assigned to a PIM group, you can remove the assignment in the PIM for Groups portal and this should resolve the issue. In PIM you would select Manage > Groups. Click on the group name to open its portal page. Click Manage > Assignments. Locate the phantom user in either the Eligible or the Active assignments and then click on the Remove hyperlink on the user's row in the table.
![image](https://github.com/user-attachments/assets/b4132f60-5854-4d3c-9a30-70b4313f9173)

**Comment by thetolkienblackguy** [comment]
- Did you or any of your team delete users recently in the tenant? Specifically users that would be assigned to a role or group that is assigned to one of the [8 roles that ScubaGear processes](https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/baselines/aad.md#highly-privileged-roles).

**Yes, I recently deleted a member of the User Administrator and Exchange Administrator roles, however, the resource throwing the error is definitely a group. I can take the objectId from the exception and query the group using graph just fine.** 
- Are you using PIM groups, or just regular Entra Id groups?

**Entra Id role assignable groups, we're assigning roles to groups that represent each team**
- Do you assign the role to the group as Active or Eligible?

**Both, less sensitive roles are assigned as Active, more sensitive roles are assigned as Eligible**
- If we develop a fix in the coming weeks, would you be able to help us alpha test it? This is assuming the error still occurs in your environment when the fix is available.

**More than happy to. Additionally, I'll attempt to recreate in another tenant and report back**

**Comment by tkol2022** [comment]
Thanks much for offering to help me test it. For now, if possible, I need your help to debug the source of the problem in your environment so that my team can make sure to create a fix that will work in your scenario. If you can perform these troubleshooting steps, I would appreciate it because it will give me the specific line # where the code is producing the error. In the near future ScubaGear will have the capability to show the stacktrace (we are working on an issue in that regard). Here is a screenshot that shows the catch block I added.

![image](https://github.com/user-attachments/assets/4edf95c6-b8b7-4b17-9b96-19bd26c82ead)

1. [Temporarily remove the ScubaGear version](https://github.com/cisagov/ScubaGear/blob/main/docs/installation/uninstall.md) that is centrally installed as a module on your system. Just run the Uninstall-Module command (no need to do the other steps on that page). This will ensure that the temporary version of ScubaGear you will install in the next steps will not conflict with the one you have centrally installed. Close any Powershell console windows that were opened when you ran ScubaGear.
2. [Go to this link on GitHub](https://github.com/cisagov/ScubaGear/tree/1288-get-privilegeduser-fails-404-message) to access the branch I created. Then click on the Code button and download the zip file to a local folder. Unzip the file to create the directory with the ScubaGear code in it.
3. Open a new Powershell window and change directory to the folder where you unzipped the downloaded file.
4. If during the execution of the next couple of steps you get warnings about running untrusted code, [follow the instructions at this link](https://github.com/cisagov/ScubaGear/blob/main/docs/installation/github.md#mark-of-the-web) to remove the warnings.
5. Import the ScubaGear module

`Import-Module -Name .\PowerShell\ScubaGear`

6. Run ScubaGear

`Invoke-Scuba -ProductNames aad`

This should produce an output similar to the following that you can take a screenshot of:

![image](https://github.com/user-attachments/assets/adbe0ccb-2304-4bb9-b4c9-4999d6c7dd44)

7. Close the Powershell window. Open a new Powershell window and re-install ScubaGear.

`Install-Module -Name ScubaGear`

Don't hesitate to ask any questions.

**Comment by thetolkienblackguy** [comment]
## Results
```
An error occurred: [Request_ResourceNotFound] : Resource '00000000-0000-0000-0000-00000000000' does not exist or one of its queried reference-property objects are not present.
Stack trace: at Get-MgBetaUser<Process>, C:\Users\REDACTED\Documents\WindowsPowerShell\Modules\Microsoft.Graph.Beta.Users\2.19.0\exports\ProxyCmdletDefinitions.ps1: line 27591
at Get-PrivilegedUser, C:\Users\REDACTED\ScubaGear\ScubaGear-1288-get-privilegeduser-fails-404-message\PowerShell\ScubaGear\Modules\Providers\ExportAADProvider.psm1: line 343
at TryCommand, C:\Users\REDACTED\ScubaGear\ScubaGear-1288-get-privilegeduser-fails-404-message\PowerShell\ScubaGear\Modules\Providers\ProviderHelpers\CommandTracker.psm1: line 22
at Export-AADProvider, C:\Users\REDACTED\ScubaGear\ScubaGear-1288-get-privilegeduser-fails-404-message\PowerShell\ScubaGear\Modules\Providers\ExportAADProvider.psm1: line 127
at Invoke-ProviderList<Process>, C:\Users\REDACTED\ScubaGear\ScubaGear-1288-get-privilegeduser-fails-404-message\PowerShell\ScubaGear\Modules\Orchestrator.psm1: line 553
at Invoke-SCuBA<Process>, C:\Users\REDACTED\ScubaGear\ScubaGear-1288-get-privilegeduser-fails-404-message\PowerShell\ScubaGear\Modules\Orchestrator.psm1: line 362
at <ScriptBlock>, <No file>: line 1
```

**Comment by tkol2022** [comment]
Thank you. Based on line where the error is occurring I think you have a group assigned to a PIM group as Eligible and the code doesn't handle that. Right now it only works if a user is assigned to a PIM group so my team will need to fix that. I was able to replicate it. Can you please let me know if what I am describing matches your environment and I will update the code in the branch so that hopefully it will get ScubaGear working for you until we officially release the update after formal testing? 

Here is my screenshot where I assigned a group to a PIM group for reference to recreate the problem.

![image](https://github.com/user-attachments/assets/ba813899-378a-404b-8d4b-e3d5489637b1)

**Comment by thetolkienblackguy** [comment]
That is actually correct. We do have a group that is assigned to a PIM group as Eligible

**Comment by tkol2022** [comment]
Thanks! As a workaround, can you assign the members of the sub group which is associated with the error directly to the PIM group?

**Comment by thetolkienblackguy** [comment]
Without getting into details, we really can't do that.

**Comment by tkol2022** [comment]
No problem. I will work with the team and discuss a fix, then get back to you next week after the holiday.

**Comment by tkol2022** [comment]
I updated the same branch with some new fix code that I worked on. Please download the zip file and try it out. Test in a new PowerShell window.
After you run the Import-Module command, you will then need to run the command below to install a new PowerShell module that is needed:

`Initialize-Scuba`

Then you can run ScubaGear.

Also, your suggestion to use Get-MgBetaDirectoryObject came in handy. I incorporated that into the new streamlined version of the code. We are grateful and you have contributed to improving the source code.

**Comment by tkol2022** [comment]
Hold off on testing. There is a logic flaw in my new function that I just thought of.

**Comment by tkol2022** [comment]
@thetolkienblackguy I just updated the branch. Can you try testing this version to see if it rectifies the error in your environment? It prints some messages to the console that I have for debugging & testing purposes - those will be removed from the final code.

**Comment by thetolkienblackguy** [comment]
@tkol2022 Will do. Won't be able to get back to you until early next week. Thank you for addressing this.

**Comment by thetolkienblackguy** [comment]
@tkol2022 My apologies, I've had other priorities, however, thank you for the reminder.  I was able to test the new branch and it no longer fails processing groups.  I haven't had a chance to look into the code, so can't provide feedback there, but it's not accurately counting the number of Global Administrators in the environment where this is being run.  Appears to be ignoring - for whatever reason - members of one group.

**Comment by tkol2022** [comment]
Thanks a lot for testing. This fix corrects the problem you were having, which was that when ScubaGear scans PIM eligible groups, it was not processing members of the group that are other groups. There was a second unrelated issue that can also generate an identical 404 message, which was that if you delete a group or a user that is eligible assigned to a PIM group, ScubaGear can crash during the hours that the phantom object stays in the PIM assignment table - Microsoft automatically cleans it up after several hours but if you run ScubaGear during that window you would get a 404.

Regarding the issue you are having with ScubaGear not counting the global administrators accurately, can you provide some details on your setup and I can try to replicate it? Also explain why you think it is not counting correctly. I will open a new issue for that once I can replicate. If you prefer to discuss offline, we can do that as well.
