### ISSUE TITLE
Identify strategy to acquire missing sharepoint 1.3 setting

### ISSUE THREAD

**Issue by Sloane4** [cisagov/ScubaGear#143]
# 💡 Summary #

_This was updated to reflect the new policy ID which is MS.SHAREPOINT.1.3v1 (old policy ID was 2.2)._

The baseline requires 'Allow only users in specific security groups to share externally' checkbox to be checked. The setting to check this is not found in `Get-SPOTenant` or `Get-SPOSite`. Need to research Microsoft documents to find it then add check to Sharepoint Rego.

## Motivation and context ##

Without check, 1.3 can produce false positives.

## Acceptance criteria ##

How do we know when this work is done?
- [x] Identify where the setting is located (i.e. REST API)
- [x] Is it possible to acquire the data with PnP or Sharepoint modules?
- [x] Develop prototype script to acquire the data via the REST API

** Acceptance criteria modified by Ted K. 2/29/2024 to reflect the actual work performed.

**Comment by Sloane4** [comment]
@tkol2022 this is the setting I was talking about in the meeting

**Comment by tkol2022** [comment]
@Sloane4 @Dylan-MITRE   I just tested this by checking the box in the admin portal to "Allow only users in specific security groups to share externally" and selecting a security group. Then I exported the provider JSON and compared it to a previous version that I had downloaded before setting the configuration. The files were identical, which confirms that this setting does not seem to be something we can check via Rego at this time. I would report this to Microsoft so that they can add the setting to the data returned from the Get-SPOTenant Cmdlet and its counterpart in the PnP module.

For the baselines, we will keep this as a policy but it can only be checked manually.

- It is only applicable when the external sharing slider is set to any value other than "Only people in your organization". This should be clear in the baseline. The same applies to the other setting "Limit external sharing by domain".
- Both OneDrive and Sharepoint should have this policy because it applies to both products.

Please let me know if there are any questions or if I missed anything.

**Comment by tkol2022** [comment]
### Reviewed 12/14
@Sloane4 @Dylan-MITRE @ssatyapal123  Please review and close if this is OBE.
If it is still valid, please assign a size label.
Hopefully my comment from May 30 can help you re-create the problem (if it still exists).

**Comment by Dylan-MITRE** [comment]
It is still valid, the provider JSON is the same still. 
Size should be relatively small if Microsoft add this setting in Get-SPOTenant. So ill add size as small for now, we can always adjust it later
I believe we have look into other sharepoint command for the right config and no luck finding it.

**Comment by twneale** [comment]
The [get sharepoint settings](https://learn.microsoft.com/en-us/graph/api/sharepointsettings-get?view=graph-rest-1.0&tabs=http) endpoint of the Microsoft graph service has some values that are related to external sharing. See the example response on that page. Does this contain the value that's needed? I tried to list the sites for y2zj1 and view the settings using the graph API and got a permission error (below) so couldn't confirm. The graph API is pretty nice from what I have seen so far. 

`{'error': {'code': 'accessDenied', 'message': "Request Doesn't have the required Permission scopes to access a site.", 'innerError': {'date': '2024-01-04T19:55:04', 'request-id': 'e67a63fc-7d34-4dbf-97b1-77548d8987db', 'client-request-id': '92bbaebb-05ba-4051-a1cb-7c14de3a2bcf'}}}`

@nanda-katikaneni Would it be possible for you to check out the permissions we have to read from the Graph API (specifically the "/sites" and "/admin/sharepoint/settings" resources) and add read permissions if missing?

**Comment by twneale** [comment]
Confirmed, this setting is available from the Graph API endpoint /admin/sharepoint/settings. The setting is **sharingCapability**: (disabled|existingExternalUserSharingOnly). 

I can be accessed with: `$(Get-MgBetaAdminSharepointSetting).SharingCapability`

I am confused about where to add it in this block below. I'm unfamiliar with the meaning of the PnPFlag and the different usages in each branch of this if statement. Can anyone educate me a bit about this? 

![Image](https://github.com/cisagov/ScubaGear/assets/70850/51291d41-c16c-4e7a-802a-6881bfb27ccb)

**Comment by Sloane4** [comment]
@twneale I recommend talking to David or Dylan, but to get you started https://pnp.github.io/powershell/index.html

**Comment by Dylan-MITRE** [comment]
I am also confused on the setting of 'SharingCapability', it changes based on the slider value, and this value is already included in the current rego script for Sharepoint 1.1
# SharingCapability == 0 Only People In Organization
# SharingCapability == 3 Existing Guests
# SharingCapability == 1 New and Existing Guests
# SharingCapability == 2 Anyone

which from my experience is not related to 1.3 settings, so you when you follow the instruction for 1.3 below and look at the json generated, did the value of SharingCapability change?
1.Sign in to the SharePoint admin center.
2. Select Policies > Sharing.
3. Expand More external sharing settings.
4. Select Limit external sharing by domain.
5. Select Add domains.
6. Add each approved external domain users are allowed to share files with.
7. Select Manage security groups
8. Add each approved security group. Members of these groups will be allowed to share files externally.
9. Select Save.

**Comment by twneale** [comment]
More on this @tkol2022. The check box and internal API endpoint both work the same way on the *sharepoint.us and *sharepoint.com instances. Authentication is the same, and the PnP rest method commandlet works the same on both. So in the case of service principal auth, we can easily fetch this setting with `Invoke-PnPSPRestMethod`. 

A problem arises in the case of interactive auth. As far as I can tell, PnP creates and uses its own in-memory cache for the access token it acquires. Since we can't use PnP for interactive auth (recall it tries to create a role with overbroad permissions. It also tries to open an IE 11 browser, which the microsoft identity platform won't even respond to, lol) there is probably no practicable way to fetch this URL with `Invoke-PnPSPRestMethod`. It's certainly possibly to send an authenticated request with a plain vanilla `Invoke-RestMethod` provided we can acquire a token to pass as the `authorization` header. I have made a relatively through search, and there doesn't appear to be any way to get the access token from the sharepoint powershell module following interactive auth. I think it also just caches it in memory, and that package doesn't provide a way to dump the access token. This seems intentional based on what I have seen from other microsoft packages. In contrast, PnP definitely provides a way to get the token. This is unfortunate, because all you really need is one token for a service like the graph API, and if you have it you can repeatedly exchange it for tokens for other services like Sharepoint without having to authenticate all over again. I don't think any of the M365 commandlets from Microsoft actually provide a way to get the token. So it may not be possible to fetch this URL without requiring interactive users to re-authenticate, and we would have to implement the interactive token acquisition ourselves or use c#. This actually isn't that hard in powershell. I already have the full flow prototyped for service principal auth. 

An alterative is just skipping this and complaining whenever the user isn't using service principal auth.

What I'm going to do next is some quick tests to rule out the possibility that the sharepoint module and PnP could be using the same token cache. I doubt it, but want to do some tests to rule out the possibility.

**Comment by twneale** [comment]
One more quick update. I did some more HTTPS traffic snooping and found that the internal endpoint returns exactly the same data as the XMLRPC endpoint that PnP uses, so any fears we have about relying on a non-guaranteed stable endpoint can be put to rest by just sending the request to the same endpoint PnP uses. That response payload from sharepoint actually includes the fields we need, but just doesn't bother serializing them into the return object.

**Comment by twneale** [comment]
To close out this issue, the setting is available through the REST endpoint used by both PnP and the Sharepoint module, but they aren't serializing it into the response, so we can't get it through either.

I was able to do a POC to get the setting via the rest API. It is somewhat elaborate in that it requires an implementation of MSAL authentication, both interactive and certificate, because an access token is required to use the API.

Two new issues follow on from this one: #957 and #958
