### ISSUE TITLE
Allow config file to override command line parameters

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#158]
Currently, command line parameters do not override config file parameters.  Doing so requires changing the parameter sets and how parameters and the configuration is processed.  Would like to see the default behavior to be such that a user could create and use a config file, but override specific settings by combining it with other command line options.  For example, if a user wants to use the same assessment parameters for both a commercial and GCC tenant, they could use the same config but override the `M365Environment` parameter on the command line for one of them without having to duplicate the config or list all parameters on the command line.

**Comment by kennethpalmer** [comment]
Here is what I am thinking to handle both default values and command line override ( this was sent in email to a few people as well, but I have refined it here.

We need to account for both the command line and the config file know if a parameter was explicitly  specified.  The command line may need to set all its default values to null in a manner similar to the config side.

The set of parameters is the union of command line options and config parameters since it may be possible a value exists for only one of the two

When both sets are looked at, the code need to see if a there is an explicit command line parameter and/or an explicit config file parameter.   If both are present the command line takes priority.  Once that has been done a composite table of explicit values and null values is constructed, and then code fills in defaults for any remaining null values ( similar to the current config code ).

**Comment by kennethpalmer** [comment]
Thanks to Richard for making me aware of $PSBoundParameters.  Looks like that would enable me to distinguish between defaults and passed in parameters.  The only question I have is that currently we have to maintain parameter defaults in the config module section which duplicates default values specified in the params.  It would be nice to be able to specify these defaults in exactly one place
