### ISSUE TITLE
Agency 4 Pilot: Exchange 2.2 false negative

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#164]
Agency 4 noted that they comply with the following policy "An SPF policy(s) that designates only these addresses as approved senders SHALL be published" but the report is showing "FAIL". Further investigation into SPF and DNS records is already underway so this may be linked.

**Comment by ethanb-cisa** [comment]
@gatesry one of our theories is this is because looking up a domain internally using an internal nameserver will return different results than looking it up externally in some cases. See [this comment](https://github.com/cisagov/ScubaGear/issues/41#issuecomment-1411086060) for more.

Do you know if this could be happening for your org? We had an idea to use DoH but that may cause other issues (proxy, etc).

**Comment by gatesry** [comment]
@ethanb-cisa We just spun up an off-domain VM; this allowed it to grab the correct SPF records.

**Comment by tkol2022** [comment]
### Reviewed 12/14
@ahuynhMITRE @adhilto Please review and close if this is OBE.
If it is still valid, please assign a size label.
I'd like to see more details in the description.

**Comment by adhilto** [comment]
Addressed by adding a DoH fallback, closing.
