### ISSUE TITLE
Enhance the PowerShell Unit Testing Invocation 

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#170]
# 💡 Summary #

Currently the PowerShell unit tests #167 take a fair amount of time to run all of the tests at once. Using a mix of smarter workflow triggers and unit test tagging we could lower the execution time enough that the test invocation will fit in a pre-commit hook.

## Motivation and context ##
To lower the scope and time it takes to run the PowerShell Unit tests.

## Implementation notes ##

Updates to the GitHub Actions workflow and maybe some of the tagging in each of the unit tests.

## Acceptance criteria ##
- The workflow triggers on only a subset of the unit tests needed for a pre-commit hook
- Execution time for the workflow as a result of the former will be increased.

**Comment by crutchfield** [comment]
#867 #890 - This Issue/PR brings the runtime don from 5-6+ minutes to less than a minute.  Further reduction would be nice if moving to a pre-commit.  But < 1 minute may be acceptable.

**Comment by crutchfield** [comment]
With changes under PR #890, time is reduced. 

![image](https://github.com/cisagov/ScubaGear/assets/7025068/877b0d0e-91a2-4409-bf13-7eca90ee32af)

**Comment by james-garriss** [comment]
The PowerShell unit tests are currently being run as part of the CI/CD pipeline.  On average, they take 45 seconds to run.  (See here for most current example:  https://github.com/cisagov/ScubaGear/actions/runs/8206837464).  It seems like this issue is OBE based upon previous work that Crutch mentioned above.  @crutchfield , @schrolla , @buidav , @nanda-katikaneni , can we close this issue as resolved?
