### ISSUE TITLE
Setup.ps1 fails because of a MicrosoftTeams dependency problem

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#176]
# 🐛 Summary #

Setup.ps1 failed when I ran it on a freshly minted virtual machine inside a GitHub Action job. The job log shows the error "No acceptable installed version found for module: MicrosoftTeams. Required Min Version: 4.9.3 | Max Version: 4.99.99999"

## Criticality Recommendation
I recommend that this get treated as a critical bug because it can prevent users from installing the tool into a working state.

## What could be causing this?
I believe Microsoft release a new version of the Teams PS module (5.0.X) which gets installed during setup. Then when you import the ScubaGear module, it is looking for a previous Teams version (4.X.X) (per the RequiredVersions.ps1) and therefore produces an error when that module is not found.

## Potential Fix
Just to see if I could resolve the error in my local branch. I updated the RequiredVersions.ps1 file as shown below and then Setup.ps1 started working. Therefore I suspect the fix is to update the version numbers in RequiredVersions.ps1.

![image](https://user-images.githubusercontent.com/107076927/223183742-8a56a89c-cd7a-4d0a-b3c3-4b21d6fe5e07.png)

 ## To reproduce ##

1. Start with a fresh machine that never had ScubaGear installed. If you are working on a previously used machine then remove the existing MicrosoftTeams module from the system.
2. Run Setup.ps1 and verify that the MicrosoftTeams 5.0.X module was installed.
3. Run "Import-Module -Name .\PowerShell\ScubaGear"
4. You should see an error message similar to what it shown in the screenshots below.

## Screenshots of the error ##

*Note: to see the error details in the log go to GitHub Actions, select the Smoke Test action and then click on the failed workflow run named "added print working directory". Then once the

![image](https://user-images.githubusercontent.com/107076927/223185822-155013a0-4c6a-49b6-9953-2379f1a53efc.png)
![image](https://user-images.githubusercontent.com/107076927/223185978-682266ec-37b6-4e70-b829-152bf8505028.png)
![image](https://user-images.githubusercontent.com/107076927/223186177-f6bc058c-00e8-47b4-b5c3-f2d73f4e575b.png)

**Comment by crutchfield** [comment]
This would be a good integration test to add to the baseline.  With a GitHub Workflow we would catch this issue earlier if we had an integration test checking it. 

 

Richard Crutchfield

Principal Software Systems Engineer

The MITRE Corporation

321-262-9246 (c)

407-737-9117 (w)

 

 <https://www.facebook.com/MITREcorp>  <https://www.linkedin.com/company/mitre>  <https://twitter.com/MITREcorp>  <https://www.youtube.com/user/mitrecorp>  <https://plus.google.com/+MitreOrgFFRDCs/posts> 

 <http://www.mitre.org/> 

 

 

From: Ted Kolovos ***@***.***> 
Sent: Monday, March 6, 2023 12:32 PM
To: cisagov/ScubaGear ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] [cisagov/ScubaGear] Setup.ps1 fails because of a MicrosoftTeams dependency problem (Issue #176)

 


🐛 Summary


Setup.ps1 failed when I ran it on a freshly minted virtual machine inside a GitHub Action job. The job log shows the error "No acceptable installed version found for module: MicrosoftTeams. Required Min Version: 4.9.3 | Max Version: 4.99.99999"


Criticality Recommendation


I recommend that this get treated as a critical bug because it can prevent users from installing the tool into a working state.


What could be causing this?


I believe Microsoft release a new version of the Teams PS module (5.0.X) which gets installed during setup. Then when you import the ScubaGear module, it is looking for a previous Teams version (4.X.X) (per the RequiredVersions.ps1) and therefore produces an error when that module is not found.


Potential Fix


Just to see if I could resolve the error in my local branch. I updated the RequiredVersions.ps1 file as shown below and then Setup.ps1 started working. Therefore I suspect the fix is to update the version numbers in RequiredVersions.ps1.

 <https://user-images.githubusercontent.com/107076927/223183742-8a56a89c-cd7a-4d0a-b3c3-4b21d6fe5e07.png> 


To reproduce


1.	Start with a fresh machine that never had ScubaGear installed. If you are working on a previously used machine then remove the existing MicrosoftTeams module from the system.
2.	Run Setup.ps1 and verify that the MicrosoftTeams 5.0.X module was installed.
3.	Run "Import-Module -Name .\PowerShell\ScubaGear"
4.	You should see an error message similar to what it shown in the screenshots below.


Screenshots of the error


*Note: to see the error details in the log go to GitHub Actions, select the Smoke Test action and then click on the failed workflow run named "added print working directory". Then once the

 <https://user-images.githubusercontent.com/107076927/223185822-155013a0-4c6a-49b6-9953-2379f1a53efc.png> 
 <https://user-images.githubusercontent.com/107076927/223185978-682266ec-37b6-4e70-b829-152bf8505028.png> 
 <https://user-images.githubusercontent.com/107076927/223186177-f6bc058c-00e8-47b4-b5c3-f2d73f4e575b.png>

**Comment by tkol2022** [comment]
@buidav Thanks. Can you create an issue to track this? If the date is rapidly approaching and will impact the stability of the tool, we can prioritize the work needed to get ready for that migration.

**Comment by tkol2022** [comment]
@crutchfield Great idea regarding the integration test!

**Comment by nicholasmhughes** [comment]
Can confirm that

```powershell
Install-Module MicrosoftTeams -MaximumVersion 4.99.99999 -force
```

after running `.\SetUp.ps1` is a valid workaround, and incorporating this limiting mechanism in that script makes a lot of sense.

**Comment by tkol2022** [comment]
@nicholasmhughes Thanks a lot!
