### ISSUE TITLE
Automate Syncing with the Baselines

### ISSUE THREAD

**Issue by ahuynhMITRE** [cisagov/ScubaGear#209]
# 💡 Summary #
Automate syncing of the group names, policy IDs, and policy contents directly from the baselines.

## Motivation and context ##

The current automation code is riddled with static references to the associated M365 product baseline policy items in multiple places. This issue is meant as an enhancement to enable automatic syncing of baseline language to pull "Group Names", "Policy IDs", & policy content from the markdown baselines into the associated testing, rego, & powershell files. 

## Implementation notes ##
- [x] #230
- [ ] #228
- [ ] #231
- [ ] Add versioned baseline links to reporter output (Use tool version to link to GitHub tagged version from repo) (#224)
- [ ] Add check for missing tests to reporter execution (https://github.com/cisagov/ScubaGear/issues/65)

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Powershell script successfully determines the baseline policy IDs and associated policy group names and policy item descriptions
- [ ] Powershell script has been successfully added to the base SCuBAGear repository
- [ ] Report displays the policy IDs and the proper group names/policy content

**Comment by adhilto** [comment]
See https://github.com/cisagov/ScubaGear/blob/baseline_versioning/PowerShell/ScubaGear/Modules/CreateReport/GetTitles.ps1 for a proof of concept for this.

**Comment by adhilto** [comment]
Breaking down this issues into the discrete tasks I see:
- [x] Create script that automatically creates the equivalent of the current `BaselineTitles.json` (that's what linked above)
- [ ] Refactor the `[product]Config.rego` files so that the `Requirement` string is automatically pulled from the json file
- [ ] Refactor the rego test cases so that they match on the policy ID instead of the requirements string
