### ISSUE TITLE
OneDrive 2.7 blocking legacy authentication is duplicative of AAD

### ISSUE THREAD

**Issue by Sloane4** [cisagov/ScubaGear#290]
# 💡 Summary #

Should this setting be kept in the OneDrive Baseline and added to SharePoint or removed

## Motivation and context ##

The user is already directed to use the setting for blocking legacy authentication in the AAD. When enabled for AAD, the blocking is applied for all Microsoft products including SharePoint & OneDrive. Should the setting be kept in OneDrive & added to SharePoint, but indicated to be selected if the are not implementing AAD baseline or as a backup? Or should this policy be removed from the OneDrive baseline. 

## Implementation notes ##

One or the other:
- Policy added to Sharepoint
- Policy removed from OneDrive

## Acceptance criteria ##

- [ ] Updated policy has the change noted in implementation notes
- [ ] OneDrive or SharePoint Code is updated to have or not have the policy check

**Comment by Sloane4** [comment]
@schrolla Who would be the appropriate person to ask? Ted?

**Comment by Sloane4** [comment]
@tkol2022 need your exp

**Comment by tkol2022** [comment]
Please delete this from the OneDrive baseline. Blocking legacy authentication is the first policy in the AAD baseline and it covers all M365 products. It is one of the most important policies across all the products and is officially cited by both Microsoft and CISA (e.g. in their SolarWinds advisories) in guidance related to securing the M365 environment. Therefore, the AAD policy is a must implement for any organization serious about hardening M365.

A couple of related thoughts:

- I am preparing a spreadsheet to perform a final adjudication of all the current Sharepoint and OneDrive policies, since there were numerous other items that may get removed. I will setup a meeting for this week to review them with you.
- In general, items that are related to Authentication or Authorization, should be in the AAD baseline. The AAD baseline is not optional for an organization securing M365 - in fact it is probably the first one that should be implemented because it provides the foundational security of the identities and how they access the system.

**Comment by gdasher** [comment]
Not commenting here based on my reading of the above--please flag anything you need CISA to decide once ready.

**Comment by tkol2022** [comment]
Closing as this was addressed in #370.
