### ISSUE TITLE
Agency 2 Pilot: OneDrive 2.4, 2.5, and 2.6; Agency Defined Domains

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#30]
Agency 2 has enabled restrictions for OneDrive for Business using a list of domains but showed "FAIL" for 2.4 and 2.6 and "PASS" for 2.5. 

There are  already ongoing discussions on possible consolidation of these policies and Microsoft has provided test scripts to run to verify findings. Testing is expected to occur post Coral.

From Ram:
1.	Set-SPOTenantSyncClientRestriction  -Enable -DomainGuids "786548DD-877B-4760-A749-6B1EFBC1190A; 877564FF-877B-4760-A749-6B1EFBC1190A"
And what is experience of Mac Sync Client on Mac for , when trying to sync OneDrive for Business. 
A.	Mac Joined to 786548DD-877B-4760-A749-6B1EFBC1190A domain - 
B. Mac Joined to domain different from "786548DD-877B-4760-A749-6B1EFBC1190A; 877564FF-877B-4760-A749-6B1EFBC1190A"
C.	Mac not joined any domain.

2.	Set-SPOTenantSyncClientRestriction  -Enable -DomainGuids "786548DD-877B-4760-A749-6B1EFBC1190A; 877564FF-877B-4760-A749-6B1EFBC1190A" -BlockMacSync:$true
And what is experience of Mac Sync Client on Mac for , when trying to sync OneDrive for Business. 
A.	Mac Joined to 786548DD-877B-4760-A749-6B1EFBC1190A domain
B.	Mac Joined to domain different from "786548DD-877B-4760-A749-6B1EFBC1190A; 877564FF-877B-4760-A749-6B1EFBC1190A"
C.	Mac not joined any domain.

3.	Set-SPOTenantSyncClientRestriction  -Enable -DomainGuids "786548DD-877B-4760-A749-6B1EFBC1190A; 877564FF-877B-4760-A749-6B1EFBC1190A" -BlockMacSync:$false
And what is experience of Mac Sync Client on Mac for , when trying to sync OneDrive for Business. 
A.	Mac Joined to 786548DD-877B-4760-A749-6B1EFBC1190A domain
B.	Mac Joined to domain different from "786548DD-877B-4760-A749-6B1EFBC1190A; 877564FF-877B-4760-A749-6B1EFBC1190A"
C.	Mac not joined any domain.

4.	Set-SPOTenantSyncClientRestriction  -BlockMacSync:$false ( with no domain specified in either enable or disable list)
And what is experience of Mac Sync Client on Mac for , when trying to sync OneDrive for Business. 
A.	Mac Joined to any domain
B.	Mac not joined to any domain. 

5.	If you run two separate commands
Set-SPOTenantSyncClientRestriction  -BlockMacSync:$true 
Set-SPOTenantSyncClientRestriction  -Enable -DomainGuids "786548DD-877B-4760-A749-6B1EFBC1190A; 877564FF-877B-4760-A749-6B1EFBC1190A" " -BlockMacSync:$false
A.	Mac Joined to 786548DD-877B-4760-A749-6B1EFBC1190A domain
B.	Mac Joined to domain different from "786548DD-877B-4760-A749-6B1EFBC1190A; 877564FF-877B-4760-A749-6B1EFBC1190A"
C.	Mac not joined any domain.

**Comment by tkol2022** [comment]
We did some hands-on testing relate to this topic and met with CISA and Microsoft to discuss the effectiveness of each one. This issue is blocked based on a final decision from CISA on which policies are going to be kept in the baseline and regarding what changes (if any) will be made to the policies. Once that decision is made, this issue will be updated with the correct scope.

**Comment by tkol2022** [comment]
My recommendation is to remove this policy from the baseline because it is not an effective control since it only applies to the OneDrive client software. Usage of the OneDrive API from other clients is excluded from the technical enforcement. I tested this and was able to circumvent the policy simply by using the OneDrive web interface.
Adversaries commonly use MS Graph based scripts in their attack campaigns - this policy would not protect against that.

**Comment by tkol2022** [comment]
Per conferring with CISA and based on security testing, OneDrive policies 2.4, 2.5 and 2.6 will be removed from the baseline. @Dylan-MITRE make sure to create an issue to modify ScubaGear accordingly. Closing this issue since the changes will be included in other issues already open in the current release.
