### ISSUE TITLE
Question - What level of guidance should the AAD baseline include for guest access w/r/t managed devices?

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#310]
# 💡 Summary #

We received feedback from #18 which provides recommendations for updates to AAD 2.17 (managed devices). Numerous suggestions were provided for CISA to create additional guidance specific to guest access and cross-tenant collaboration settings (including trusting claims from other tenants).

Currently AAD 2.17 includes a paragraph about guest access when describing the policy and provides specific implementation steps for configuring cross-tenant collaboration settings to facilitate the sharing of MFA and device claims across tenants. The sharing of claims is necessary so that the resource (aka target) tenant can determine if the guest user meets the requirements of the conditional access policy requiring a managed device.

## Questions to CISA ##

The details of cross-tenant access and how it can be implemented may be outside the scope of the AAD baseline. This is because there are numerous collaboration use cases, each with its own technical implementation and CISA may not be able to prescribe a one-size-fits-all set of cross-tenant access settings that will work for most agencies.

- Does CISA want to provide detailed technical implementation (prescriptive) steps on configuring cross-tenant access as we do today? Our recommendation is to replace the existing prescriptive guidance with a more general description that cross-tenant access needs to be configured to share claims about devices (and MFA) across tenants and avoid being prescriptive.
- One of the suggestions from the feedback is "Providing guidance on how home tenant ISOs should supply their security baseline reports as evidence to resource tenant ISOs through Interagency agreements (or some other medium)." CISA's response?
- Response to any of the other points or suggested actions provided in feedback issue #18?

**Comment by gdasher** [comment]
_Does CISA want to provide detailed technical implementation (prescriptive) steps on configuring cross-tenant access as we do today? Our recommendation is to replace the existing prescriptive guidance with a more general description that cross-tenant access needs to be configured to share claims about devices (and MFA) across tenants and avoid being prescriptive._

I think the recommendation is reasonable.  2.18 also hits on this (guest accounts).  I think having a section on "security considerations" in 2.17 and 2.18 that provides non-normative guidance on this topic is sensible since they are subtle and complicated.  I know we've normally shied away from that but in this case I think it adds value.

_One of the suggestions from the feedback is "Providing guidance on how home tenant ISOs should supply their security baseline reports as evidence to resource tenant ISOs through Interagency agreements (or some other medium)." CISA's response?_

I think this is too compliance focused for the baselines.  I think we could note that, in general, some amount of trust relationship needs to be established and that the baseline reports could help build that trust in some situations.

**Comment by tkol2022** [comment]
Item #327 was created to make the respective changes to the baseline document.
