### ISSUE TITLE
Explore how to improve the execution performance of the Azure AD provider

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#35]
The Azure AD export provider is by far the longest of all the products and can take over a minute.
I ran a profiler tool and determined that most of the time in this provider is spent executing in the functions Get-PrivilegedUser and Get-PrivilegedRole. Both of those functions have loops and inside the loops, calls to back-end M365 services are called.

This issue is to explore if there's a way we can make significant improvements to the execution time by exploring alternative provider export algorithms. The ideal outcome of this issue would be a code prototype.

**Comment by tkol2022** [comment]
### Background

- While working on this issue I gathered detailed timings of all the code execution during an Azure AD run using a profiler and the Powershell Measure-Command cmdlet which can time individual lines of code.
- I also timed the overall execution time of ScubaGear (including when running all the products together) under different scenarios. For example I compared how long it takes to run ScubaGear with the authentication popup prompts (the default) versus without the authentication prompts (using the -LogIn $false parameter).
- I ran the tests and sample fix code on my laptop and on a remote virtual machine that has less CPU and memory. In general I found that running ScubaGear on the remote virtual machine was significantly slower compared to my laptop. The virtual machine provided a good test environment to test performance improvements since we know that some users will need to use machines with less resources than my development laptop which has plenty of memory and a decent CPU.

**Comment by tkol2022** [comment]
### Select-MgProfile cmdlet performance problems

One of the items that I discovered when timing ScubaGear, is that the tool seemed to run significantly faster when running without the authentication prompts via the -Login $false parameter. I compared how long it takes to run the tool with the Connect-Tenant function being called (which is the default) versus to run the tool with -Login $false (no invocation of Connect-Tenant). 

_When I ran with the authentication prompts to gather timing information, I made sure to enter my credentials and have them saved to the authentication cache before performing the measurements. This was achieved by logging into ScubaGear once in a new Powershell window and then beginning the measurements after the second run. Therefore I removed any time that I spent entering the user/pass/MFA from the profiling measurements. I also ran each of the scenarios several times in a loop to take an "average" time measurement._

Below shows how long it took to run with Connect-Tenant and without Connect-Tenant (referred to as No Login) on **my machine**. Time difference of 9 seconds on average.
![invokeScubaLaptop](https://user-images.githubusercontent.com/107076927/218175771-e8414299-44ba-43b3-9ad8-d43359b4d1b9.PNG)


Below shows how long it took to run with Connect-Tenant and without Connect-Tenant (referred to as No Login) on the **virtual machine**. Time difference of 15 seconds on average.
![invokeScubaVirtualMachine](https://user-images.githubusercontent.com/107076927/218175949-3f71cbfe-47b5-4fa6-be83-d577cc66e566.PNG)

**Reasons why this was happening**
Although I expected there to be a time difference between running with and without Connect-Tenant, the difference was large enough that I decided to investigate the timing of each individual line of code in Connect-Tenant to determine where the time was being spent in the function. I found that the **Select-MgProfile cmdlet** was the culprit. This cmdlet is used to switch to the Beta MS Graph cloud endpoint which is required to run ScubaGear. Interestingly I found that this cmdlet was fast the first time, but then got subsequently slower upon each invocation of ScubaGear.

See the screenshot from the virtual machine which shows how Select-MgProfile slows down each time the tool is run:
![selectMgProfile Slow virtual machine](https://user-images.githubusercontent.com/107076927/218181159-0c35601a-4412-4081-b2d1-b69b5b05fa21.PNG)

Here is on my machine:
![selectMgProfile Slow laptop](https://user-images.githubusercontent.com/107076927/218181202-390c876b-f186-4659-88b2-fe97f587c7f0.PNG)

### The Fix
Luckily for us, there was a workaround to correct this problem in ScubaGear. The fix was to check if the Beta endpoint was already selected (from a previous invocation of ScubaGear) and then avoid selecting it again when not necessary. This will hopefully shave off a decent amount of time when running ScubaGear multiple times in the same Powershell window. @buidav was gracious enough to include the fix [in his pull request](https://github.com/cisagov/ScubaGear/pull/146) related to service principals so it is now in the main branch. The fix code is below for reference.

```
$GraphProfile = (Get-MgProfile -ErrorAction "Stop").Name
if ($GraphProfile.ToLower() -ne "beta") {
    Select-MgProfile -Name "Beta" -ErrorAction "Stop" | Out-Null
}

```

**Comment by tkol2022** [comment]
In addition to the Select-MgProfile fix described earlier, code enhancements were made to the ExportAADProvider file to reduce the number of network calls to M365 APIs, which makes the code run faster on a machine with less resources and in cases where a tenant has lots of privileged users. See #155 for details.
