### ISSUE TITLE
Split Azure AD 2.15 role activation approval into two policies

### ISSUE THREAD

**Issue by tkol2022** [cisagov/ScubaGear#374]
# 💡 Summary #

The existing Azure AD policy "2.15 Activation of Highly Privileged Roles SHOULD Require Approval" requires an approval for all of the privileged roles.

Although this is great for security in theory, it may be burdensome to expect it for most organizations since there is operational overhead involved with performing approvals.

The goal of this issue is to split the policy into two, one for Global Administrator and one for the other roles. I think it is reasonable to expect most organizations to enforce and execute an approval to activate users into the Global Administrator role because it is such a high risk role. This would become a SHALL policy.

For the other roles, I would think approval makes more sense for highly sensitive tenants but not necessarily for all tenants.
I think making Global Admin approval into its own policy also provides organizations with a reasonable target to strive for and monitor via Scuba Gear.

## Implementation notes ##
Split policy 2.15 into the following two policies.

- [x] Activation of the Global Administrator role SHALL Require Approval
- [ ] Activation of the other Highly Privileged Roles SHOULD Require Approval
- [ ] Open a separate issue for the respective code changes

**Comment by tkol2022** [comment]
I placed this into Flipper because we have our hands full right now.

**Comment by ssatyapal123** [comment]
@tkol2022 It looks like the first task of this issue has been addressed in Emerald by policy:
_**MS.AAD.7.6v1** Activation of the Global Administrator role SHALL require approval._
Perhaps this issue was not closed and moved to "Done" status.
However, the second task doesn't have a policy associated:
_Activation of the other Highly Privileged Roles SHOULD Require Approval_
Do you think we should we include a new policy for this, and implement it in the code?

**Comment by tkol2022** [comment]
Let's close this for now, based on feedback from CISA. We have higher priority enhancements and fixes.

**Comment by ssatyapal123** [comment]
Closing issue per feedback from CISA
