### ISSUE TITLE
Implement better DNS Retry logic (Agency 2 Pilot: EXO 2.4; DMARC Failures)

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#38]
Agency 2 manages their DMARC policy outside of EXO but could still verify they meet the policy via DNS lookups. We should investigate why they failed.

**Comment by gdasher** [comment]
The DMARC policy in the rego is based purely on  DNS.  Looking at Agency 2 and Agency 1's data, the DNS results are not being correctly populated for a subset of their domains, perhaps due to transient errors.  

I believe the appropriate fix for this issue is better retry logic for DMARC.  I am retitling the bug as soon and unassigning from me for prioritization of implementation in Dolphin (or deferral to later release).

**Comment by gdasher** [comment]
Specifically, on transient DNS failures, we should retry as well as differentiate this error condition from NXDOMAIN.

**Comment by gdasher** [comment]
Closing as duplicate of #41
