### ISSUE TITLE
Getting stuck at the AAD category by prompted for several sign-ins without getting any further

### ISSUE THREAD

**Issue by cloudsecsebttc** [cisagov/ScubaGear#380]
# 🐛 Summary #

What's wrong? Please be specific.

When running the latest version, 0.3, I am getting prompted by signing in at the AAD stage a lot of time, but does not come any further. After several attempts of clicking on my user that is signed in, and a GA, I get the error message: Could not log you in - but thats after clicking login 10+ times. I have to cancel the sign-in prompt a few times before it goes further and give me a report with a lot of errors from the AAD category  

I have tried to run the tool several time, but it always occurs. My PS is in administrator mode. 

Below are the errors from the console

## To reproduce ##

Run the tool over and over again, in different consoles, but did not work either

## Expected behavior ##

What did you expect to happen that didn't?

Expected to be promted for sign-ins, but not as many as here, and at the end getting error: Could not sign you in

## Any helpful log output or screenshots ##

Paste the results here:

WARNING: Error running Get-PrivilegedUser. A task was canceled.
WARNING: Error running Get-PrivilegedRole. Code: generalException
Message: Unexpected exception occurred while authenticating the request.

WARNING: Error running Get-MgPolicyAuthorizationPolicy. Code: generalException
Message: Unexpected exception occurred while authenticating the request.

```

Add any screenshots of the problem here.

**Comment by tkol2022** [comment]
I have had similar issues with logging into AAD many times, at random moments. Here are some things you can try in order and then report back to let us know if it worked. After each item below, try running the ScubaGear again.

1) First run Disconnect-SCuBATenant before you do anything else. This clears the local authentication cache that the Graph modules store on disk. I have found that even when you open a new Powershell window the session still needs to get cleaned up. 
2) Reboot the machine. I had some Graph module versioning issues lately on a couple of different machines that I ended up having to reboot in order to fix.
3) Uninstall the tool by running ".\utils\UninstallModules.ps1". Make sure that Microsoft.Graph.Authentication was removed because that is often the offending module. If you have a hard time removing it, try rebooting and then run the uninstaller again. Then re-install the tool by running .\Setup.ps1

If this does not work, run the diagnostic script ".\utils\ScubaGearSupport.ps1 and upload the output zip file so we can take a look at it. It will list which module versions you have installed.

**Comment by angibson** [comment]
Thanks for this guidance. I'll work with my customer to go through these steps and will let you know the results.




Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by angibson** [comment]
Team,

Here's a reply from my customer:

Answers in-line.

 What version of PowerShell are you using? i.e 5.1 or 7?   Version 5.1
What versions of the Microsoft Graph PowerShell modules are you using? Run Get-InstalledModule and look for the Microsoft.Graph.* modules.  Mostly version 1.17 but some 1.28 as well.



I’m also planning to follow the guidance in your follow-up email.





Ben Kellerman

Department of Homeland Security/U.S. Customs & Border Protection
Windows Services Group (WSG)
Data Center Operations (DCO) | EDCOG | EIOD

Cell 703-930-6489

**Comment by cloudsecsebttc** [comment]
> I have had similar issues with logging into AAD many times, at random moments. Here are some things you can try in order and then report back to let us know if it worked. After each item below, try running the ScubaGear again.
> 
> 1. First run Disconnect-SCuBATenant before you do anything else. This clears the local authentication cache that the Graph modules store on disk. I have found that even when you open a new Powershell window the session still needs to get cleaned up.
> 2. Reboot the machine. I had some Graph module versioning issues lately on a couple of different machines that I ended up having to reboot in order to fix.
> 3. Uninstall the tool by running ".\utils\UninstallModules.ps1". Make sure that Microsoft.Graph.Authentication was removed because that is often the offending module. If you have a hard time removing it, try rebooting and then run the uninstaller again. Then re-install the tool by running .\Setup.ps1
> 
> If this does not work, run the diagnostic script ".\utils\ScubaGearSupport.ps1 and upload the output zip file so we can take a look at it. It will list which module versions you have installed.

This helped me solve this issue! Disconnect-SCuBATenant worked, thanks a lot
