### ISSUE TITLE
Support Assignment Exclusions for Conditional Access Policies

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#54]
Updated AAD policy and unit tests to define policy for users, groups, and roles, and to test for any exclusions to these.
Policy updates were made to 2.1, 2.2, 2.3, 2.4, 2.9, 2.10, and 2.13.

Policy 2.17 involves hybrid joined and compliant devices and is unchanged. This is the only "should" vs "shall" requirement, and we are not currently applying these policies in the tenant configurations.

**Comment by ssatyapal123** [comment]
Started examining the failures that occur when running this code against the cisaent (G5) tenant. All policies impacted (2.1, 2.2, 2.3, 2.4, 2.9, 2.10, 2.13 fail as expected, due to user/group/role exclusions). (See attached.)

Possible next steps include capturing the policy failures and identifying terms needed to define the allowable exclusions in Rego (those that the user can include in a config file).
[Azure Active Directory Baseline Report_CAP_ss.pdf](https://github.com/cisagov/ScubaGear/files/10512156/Azure.Active.Directory.Baseline.Report_CAP_ss.pdf)
