### ISSUE TITLE
Explore switching back our Run OPA tests action from back from < 0.50 to latest 

### ISSUE THREAD

**Issue by buidav** [cisagov/ScubaGear#593]
# 💡 Summary #

Back during the 0.30 release we had to switch the Run OPA tests workflow from `latest` to `< .50`  #193.
Over the course of the Emerald release, we've might've solved this issue with our Rego code updates. 
This issue is to see if we can switch back from `< .50`  to `latest`.
<img width="235" alt="run check" src="https://github.com/cisagov/ScubaGear/assets/105074908/2de79723-a21f-4744-8419-a8e88f3c9717">

## Motivation and context ##
To revert a change we made because we were out of compliance with OPA standards. 

## Implementation notes ##
Change that variable and see if our current rego code still fails.

## Acceptance criteria ##
- [ ]  `< 0.50` => `latest` in `run_opa_tests.yaml`

**Comment by mitchelbaker-cisa** [comment]
Changing the OPA version from <0.50 to latest in run_opa_tests.yaml throws the same errors which are fixed in #631. Once this PR is merged then we should be fine switching the test action back to latest. (I pulled my changes from this PR to double check and the test action passes successfully)

![Screenshot 2023-11-16 172417](https://github.com/cisagov/ScubaGear/assets/149098823/3e2e816b-d3bd-4b33-b21b-a5d650c76238)
