### ISSUE TITLE
Hands-on test of how the Disable SMTP AUTH EXO policy overlaps with AAD Block Legacy Authentication policy

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#607]
As a follow up to this PR, I'd like us to perform a hands-on test of enabling SMTP AUTH for a test user's mailbox and see if it is possible to authenticate to the tenant with only username/password (no MFA). Since we have legacy auth disabled by AAD policy 1.1 in our test tenants via a conditional access policy and that CA policy applies to all apps including EXO, I would like to see how the system will behave. Will the AAD conditional access policy block the authentication without MFA or will it be allowed because SMTP AUTH was enabled on the test mailbox? This will help us understand the scope and interrelationship between these policies and associated risks. Feel free to create a new issue if appropriate. Thank you.

_Originally posted by @tkol2022 in https://github.com/cisagov/ScubaGear/pull/606#pullrequestreview-1690323478_

The scope of this issue is to perform hands-on prototyping to understand:
- How the MS.EXO.5.1v1 SMTP AUTH SHALL be disabled policy works in practice?
- What is the interaction between enabling/disabling SMTP in Exchange Online at the organization versus the user level?
- What overlap do the Exchange Online configurations have with AAD policies MS.AAD.1.1v1 Legacy authentication SHALL be blocked and MS.AAD.3.1v1 / MS.AAD.3.2v1 which require MFA?
- Is there a need to have both the AAD policies and the EXO policies or are the AAD policies technologically sufficient?

**Comment by tkol2022** [comment]
### Test Results

Details are provided in this spreadsheet.
[EXO SMTP AUTH testing.xlsx](https://github.com/cisagov/ScubaGear/files/14043250/EXO.SMTP.AUTH.testing.xlsx)

- The only way that I was able to send an SMTP email with just username & password was by enabling SMTP AUTH at the organization level, enabling it at the user level and adding the user to an exclusion in the conditional access policies that block legacy authentication and require MFA.
- It is possible to block legacy authentication for SMTP and require the use of MFA by only having the conditional access policies. The Exchange configurations are not technically necessary.

The screenshots below correspond to test case 4 in the spreadsheet. In this test, the Exchange Online configurations were set to allow SMTP Auth at the organization and user level, but the conditional access policies were enforced (the user was not excluded from the CA policies). You can see that AAD blocked the SMTP request because it applied two CA policies (one that blocks legacy authentication and one that requires MFA to authenticate).

![SMTP user password fails when CA is on](https://github.com/cisagov/ScubaGear/assets/107076927/7d38008f-87f7-4c55-af7a-cbd2ce2a5034)

![CA policy blocks SMTP 1](https://github.com/cisagov/ScubaGear/assets/107076927/b8549f9c-09c1-4745-b491-9dd84f68469c)
![CA policy blocks SMTP 2](https://github.com/cisagov/ScubaGear/assets/107076927/8c8a9f82-5ac9-4fd6-9ece-d6d914aa98a7)
![CA policy blocks SMTP 3](https://github.com/cisagov/ScubaGear/assets/107076927/b915944a-29d8-400b-9fd3-c238dbcf17cd)
![CA policy blocks SMTP 4](https://github.com/cisagov/ScubaGear/assets/107076927/241d1e2f-c8c2-4ff2-93e5-3e7307596fa3)

![SMTP AUTH enabled organization level](https://github.com/cisagov/ScubaGear/assets/107076927/5c744e1d-2fb3-41b2-b09b-9a06793a7bf7)
![authenticated SMTP enabled user level](https://github.com/cisagov/ScubaGear/assets/107076927/70cbf792-bedf-44df-8c81-8e10aca531f1)

**Comment by tkol2022** [comment]
### Issue with EXO baseline instructions
Via testing this I uncovered an inconsistency with the [implementation instructions for MS.EXO.5.1v1](https://github.com/cisagov/ScubaGear/blob/main/baselines/exo.md#msexo51v1-instructions).

![image](https://github.com/cisagov/ScubaGear/assets/107076927/b317b86e-d191-4ca0-82e7-b8a4e6130a22)


- The optional steps in that section direct the reader to set the Authenticated SMTP to enabled for the user that is an exception to the policy. In other words, if an organization wants to make an exception for a specific user's mailbox and allow that user to send mails with only username and password with SMTP, they should set that user's Authenticated SMTP value to Enabled. I found out that if the organizational setting for SMTP AUTH is set to Disabled, then setting the user's value will NOT allow them to send SMTP emails with username password. The organizational setting must also be set to Enabled.
- We may need to correct this in the documentation, but instead refer to the Discussion & Decision section below for my recommendation.

**Comment by tkol2022** [comment]
### Discussion

- Based on the information documented above you can see that MS.EXO.5.1v1 is not technically necessary because of AAD policies MS.AAD.1.1v1 and MS.AAD.3.1v1 / MS.AAD.3.2v1.
- The EXO policy is specific to email and the SMTP protocol, whereas the AAD policies apply to all M365 applications and in the case of email and blocking legacy authentication, they apply to SMTP, IMAP, POP and other protocols. The AAD policies are more comprehensive.
- You will also see that our baseline provides instructions in the case that an exception must be made to allow a specific user's mailbox to send SMTP emails authenticated with only username / password. One would think that this would be edge cases such as devices that do not support MFA. The instructions that we provide to configure an exception will not work for two reasons. One, because the EXO organizational setting must also enable SMTP AUTH, not just at the user level. Second, even if it were possible to make an exception for a specific mailbox in EXO, our AAD conditional access policies will block the SMTP authentication requests as evidenced by the tests that were executed. AAD supports user exclusions via a ScubaGear config file.

### Decision

- Do we still need the EXO policy to block SMTP username password authentication given the points above? 
- If we keep the EXO policy it would be "extra" since the enforcement of what we are looking for is handled by AAD conditional access.
- Whether we keep the policy or not, to support exceptions (i.e. mailbox needs SMTP auth), the follow conditions would need to be met. The admin would need to exclude the specific user who's mailbox needs SMTP auth in the AAD conditional access policies. We have numerous CA policies. Also in EXO the organizational SMTP AUTH would need to be enabled and the user's Authenticated SMTP value would need to be enabled. Because it is probably not a good idea to direct an admin to enable SMTP AUTH at the organizational level in EXO we may want to reconsider providing instructions for exceptions.

**Comment by tkol2022** [comment]
Pinging @gdasher @buidav @schrolla @nanda-katikaneni @ahuynhMITRE @adhilto for review. Will discuss at stand-up parking lots.

**Comment by adhilto** [comment]
I would vote for keeping MS.EXO.5.1v1. Even though CAP policies block this as well, blocking it using the EXO setting could be seen as a defense in-depth thing. And it's possible we have some users who, thinking they the just care about hardening EXO, don't look at the other baselines. Keeping it would ensure the strongest possible configuration, regardless of how they're handling AAD.

That said, I would be in favor for removing the bit about allowing exceptions for individual mailboxes, given that that is not actually technically feasible.

**Comment by ahuynhMITRE** [comment]
agree with @adhilto in the off chance that a user is only looking at the EXO baseline. Since the two policies can co-exist it would mainly act as an "extra" policy.

We could also update the policy to point to the AAD policies like we have with a couple of EXO/Teams -> Defender policies.

**Comment by tkol2022** [comment]
@adhilto can u make an issue to revise the EXO baseline per the result of this issue? once that is created, please close this issue with a comment pointing to the new one. thank u!

**Comment by adhilto** [comment]
Change to the EXO baseline now tracked as https://github.com/cisagov/ScubaGear/issues/915.
