### ISSUE TITLE
Explore Replacing the SharePoint PowerShell module with PnP.PowerShell

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#63]
While looking at M365DSC I noticed that they are not using the official SharePoint PowerShell module. 
They are using the [PnP.PowerShell](https://pnp.github.io/powershell/) module for their SharePoint/OneDrive related resources. 

From a cursory look it seems like it's more fully featured compared to the regular SharePoint PowerShell module and includes Service Principal support that the regular SPO PowerShell module lacks.

**Comment by tkol2022** [comment]
For this issue, there are two scope items:

1. Make sure that the Sharepoint PnP Powershell module can fetch the configuration data needed to support the Rego policies for **Sharepoint and OneDrive** since they both currently use the same module. If the PnP module does not support the configuration settings that we inspect in the Rego, then it is not a viable alternative to transition to.
2. Make sure that the Sharepoint PnP Powershell module works with a service principal. This requires setting up an application in Azure AD as the service principal and testing from Powershell to make sure that we can authenticate using the service principal credential.

**Comment by Sloane4** [comment]
**Evaluation**
All settings needed for Rego is found in JSON output if marked with a check mark.

### SPO Provider:
- [x] Get-SPOTenant => Get-PnPTenant
- [x] Get-SPOSite => Get-PnPTenantSite

### OneDrive Provider
- [x] Get-SPOTenantSyncClientRestriction => Get-PnPTenantSyncClientRestriction
- [ ] Get-SPOTenant => Get-PnPTenant `Missing OneDriveLoopSharingCapability for Baseline 2.1: Policy 1`
- [x] Get-SPOSite => Get-PnPTenantSite `Not used in Rego`
