### ISSUE TITLE
HTML report links to GitHub main branch baselines rather than versioned baselines

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#654]
Do we want the link at the top right to point to the versioned baselines? Currently it just points to main.
![image](https://github.com/cisagov/ScubaGear/assets/106177711/49fbfa2c-c14d-4ef3-9a3e-2be5f2e1aeea)

I think pointing to the versioned baselines might be better, but I don't have strong feelings about it. Everything else looks good.

_Originally posted by @adhilto in https://github.com/cisagov/ScubaGear/issues/651#issuecomment-1804301488_

**Comment by isab-m** [comment]
> Additionally, the main branch baseline link is hard coded into both the parent and individual templates right now to the main branch. So the fix gets a bit more involved, but changing the New-Report method to search for a new {BASELINE_URL} template and doing the search and replace could work. It isn't terribly difficult, but requires some thought and testing.

Have done some work on this and ran into something with the urls. 


![Image](https://github.com/cisagov/ScubaGear/assets/137103213/cd55310f-9d81-4dd9-be8c-97cd47f5970e)


![Image](https://github.com/cisagov/ScubaGear/assets/137103213/2cdf07f6-7ec0-418c-9f3d-19864526cfb7)


![Image](https://github.com/cisagov/ScubaGear/assets/137103213/3f19e6a7-c6eb-475e-be31-dd1ce9bf33c1)

I believe the cause for this 404 is from this commit from PR #802
https://github.com/cisagov/ScubaGear/pull/802/files#diff-6202652ff4864151d5a7c7986072e0a610d2c96405454453cc720024732720c6


Would we want to ignore this 404 issue since the baselines are moved to a different location for the new release? I ask because I'm using a similar code line to the commit above to do the {BASELINE_URL} replace in the individual template and testing that line is giving me the same 404 issue.
