### ISSUE TITLE
Conduct details testing of PowerPlatform with a mix of user roles and licenses

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#69]
### Main problem
After testing in various environments and with different user role levels (including with and without PowerApps license), we have identified that PowerPlatform does not always produce an output report that a user can rely on to have accurate results. We have also seen problems when the user mistakenly sets the wrong Endpoint parameter value (e.g. they run against a commercial tenant but have "usgov" as the endpoint).

### Scope of this issue

- Test the automation tool against PowerPlatform with a combination of user/license/endpoint conditions and document the results in a spreadsheet.
- Test these combinations against a variety of tenants and document the results for each tenant

To work on this issue, we will need to create test accounts so that whomever is working on this issue can use those credentials to run the tests.

### Outcomes
The test results may generate a new bug fix issue to address the problems noted from this work.

### Testing Format
Please use the spreadsheet below to record your results. I put an example set of conditions in the first tab. These can be replicated to the other tabs (for other tenants). Make sure to note which type of machine you used to test with.
See PowerPlatform test results in original issue #304

**Comment by tkol2022** [comment]
### Summary of my Findings
I tested various cases as documented below to trigger scenarios where the report is incorrect and/or is missing policies. Please repeat my tests to confirm these findings. The findings described here influence the implementation of #67 which should address the problems using custom error handling logic for the 403 conditions.

- A Power Apps license must be assigned to the user running the tool otherwise the cmdlets Get-DlpPolicy and Get-PowerAppTenantIsolationPolicy will return a 403 with the error message "The user does not have an entitlement to use PowerApps". This error does not raise an exception that stops execution of the tool. Instead the cmdlets will return a JSON structure that contains a StatusCode field with the value 403.
- The Power Platform Administrator role is required to retrieve the policy 2.3 tenant isolation setting. Otherwise the Cmdlet Get-PowerAppTenantIsolationPolicy will return a 403 and the error message "User is not a tenant admin."
- If the user runs the tool as Global Admin the Power Apps user license is not needed.
- If the user is not a Global Admin, they must have both the Power Platform Administrator role and a Power Apps license assigned. The current README user permissions section is accurate.
- If the user is running against a GCC tenant, they must pass the -M365Environment gcc parameter, otherwise a 403 is returned as described in the first bullet above. Discuss with @ethanb-cisa since this implies that running the tool with the default parameters and forgetting to pass the environment parameter will result in errors for government users since by default the tool executes against the commercial PP endpoint.

### Test Cases Conducted

- Case 1 - Test when the user has no role and no Power Apps license
- Case 2 - Test when the user has Global Reader role and no Power Apps license
- Case 3 - Test when the user has Power Platform Admin role and no Power Apps license
- Case 4 - Test when the user has no role but has the Power Apps license
- Case 5 - Test when the user has Power Platform Admin role and Power Apps license
- Case 6 - Test when the user has Global Admin role

Note: when testing I found it was better to create a separate test user for each case because I had problems with credential permission caching when trying to use a single test user and the results.
