### ISSUE TITLE
Azure AD functional release testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#830]
# 💡 Summary #

As part of Flipper release, several Rego assessment components have been refactored.  To ensure that the tool's update is accurate, detailed functional testing has been planned. Each policy will be functionally tested to check that all pass/fail scenarios have been correctly processed by the tool using existing automated functional test plans.

This issue functionally tests each policy of the Azure AD baseline of ScubaGear tool. The main objective is to test Azure AD policies and ensure that ScubaGear tool is providing the correct result for each configuration option. 

## Motivation and context ##
This functional testing ensures that ScubaGear results of pass/fail are accurate based on the latest version of the code.

## Implementation notes ##
To perform functional testing, do the following:

- [x] Configure the automated testing and run against each tenant type for which a variant testplan is present.  Run the automated test plans (e.g. regular, g5, etc.) and note the results.
- [x] For each test failure, investigate and note the cause of the failure and log any new issues needed to resolve

For details on how to use and execute the functional tests, please see #592 or reach out to the dev team via other channels.

## Acceptance criteria ##

- [x] All existing test plan variants for the product have been successfully run
- [x] Testplan results have been reviewed and any issues resolved or reported as new issues

**Comment by tkol2022** [comment]
### MS.AAD.3.2v1 functional test is not passing
 @Sloane4 - please see if you can recreate and help debug this one.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/2b70b9ab-4115-4e37-89b3-17dab21acb78)

**Comment by Sloane4** [comment]
I got the same error through just running the functional test
![image](https://github.com/cisagov/ScubaGear/assets/47129205/1bbb8821-3670-4260-9e9d-b0bc220cfd57)
I take a closer look at the code

**Comment by Sloane4** [comment]
It might have something to do with report details, because when I looked at the relevant test results json I found `"ReportDetails":  "11 conditional access policy(s) found that meet(s) all requirements:**\u003cbr/\u003e**Automated Test 1 - DO NOT MODIFY, Internal Operations - Block CAP Exclusion Test Accounts, Internal Operations - Prevent Persistent Sessions **\u0026** Enforce Sign-in Frequency, MS.AAD.1.1v1 Legacy authentication SHALL be blocked, MS.AAD.2.1v1 Users detected as high risk SHALL be blocked, MS.AAD.2.3v1 Sign-ins detected as high risk SHALL be blocked, MS.AAD.3.2v1 If phishing-resistant MFA has not been enforced, an alternative MFA method SHALL be enforced for all users, Manual Test - Block Azure management for specific users, Manual Test - Managed device required for MFA registration (test users), Manual Test - Require CBA (test users), Manual Test - Require Device Signal (test users). \u003ca href=\u0027#caps\u0027\u003eView all CA policies\u003c/a\u003e."`

**Comment by nanda-katikaneni** [comment]
Adding @isab-m for awareness (as she worked on couple reporting issues recently).

**Comment by tkol2022** [comment]
### 5.4 failing
AAD functional test (compliant case) is failing against GCC High - currently looking into it.

![image](https://github.com/cisagov/ScubaGear/assets/107076927/126e443a-aa69-4f1e-ba7d-03aee93448b2)

**Comment by tkol2022** [comment]
@Sloane4 Kindly open a separate issue to fix the functional test related to the unicode character.

**Comment by tkol2022** [comment]
### Testing Summary

- Tests were run again all four test tenants, including e5, g5, g3 and gcc high.
- Found a bug in the functional test for 3.2 - separate issue to take care of it - not show stopper for release.
- Found a bug in AAD 5.4. The Get-MgBetaDirectorySetting was not working in GCC High but turns out it was ephemeral, as characterized by David. It is working now. No problem to fix for us right now.
