### ISSUE TITLE
PowerShell Unit Testing

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#85]
The orchestrator refactor a while back encapsulated most of the PowerShell logic within testable functions/cmdlets. 
While unit testing the Provider extractions may not possible, we are able to test the rest of the PowerShell logic with something like [Pester](https://github.com/pester/Pester) and passing in mock Provider JSON data.

**Comment by rgbrow1949** [comment]
For the hackathon, we split the original Orchestrator unit test file into components for modularity and updated the components to the new Orchestrator logic. 

Our plan now is to 
- Mock-up commandlets instead of calling them
- Create a config file to use variables instead of hard-coding for values like filepaths
- Make sure the unit tests work for all products.
