### ISSUE TITLE
Get-SPOTenant throws error, preventing Sharepoint from being scanned.

### ISSUE THREAD

**Issue by kmcdermott7777** [cisagov/ScubaGear#889]
# 🐛 Summary #

What's wrong? Please be specific.

Get-SPOTenant throws error, preventing Sharepoint from being scanned.

WARNING: Error running Get-SPOTenant. Unable to cast object of type 'System.String' to type
'Microsoft.Online.SharePoint.TenantAdministration.EsignatureThirdPartyProvidersInfo'.

1. Invoke-SCuBA, which at some point will run a Get-SPOTenant command

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

WARNING: Error running Get-SPOTenant. Unable to cast object of type 'System.String' to type
'Microsoft.Online.SharePoint.TenantAdministration.EsignatureThirdPartyProvidersInfo'.

```console

```

Add any screenshots of the problem here.

**Comment by gdasher** [comment]
Thanks for reporting!  If you run `Get-SPOTenant` outside scubagear do you also get the same error?  Like this:

```
$AdminSiteURL="https://mysite.sharepoint.com"
 
Connect-SPOService -Url $AdminSiteURL 
 
Get-SPOTenant
```

If no error, if you'd be able to share a redacted version of the config around anything that speaks to _EsignatureThirdPartyProvidersInfo_ that would be helpful.  I don't see much about that type online so it might be a somewhat obscure feature that is interacting badly with the Powershell Module (or otherwise).

**Comment by jmil-dev** [comment]
It looks like there might be a problem with the latest version of Microsoft.Online.SharePoint.PowerShell. I've had exactly the same problem while trying to run Set-SPOTenant if I run Set-SPOTenant -AllowAnonymousMeetingParticipantsToAccessWhiteboards On I get the same error which has only two results on Google (this is one..).

Downgrading Microsoft.Online.SharePoint.PowerShell to 16.0.24322.12000 fixes the problem.
