### ISSUE TITLE
OPA output function fails due to escape sequence

### ISSUE THREAD

**Issue by Rost9220** [cisagov/ScubaGear#935]
# 🐛 Summary #
Gets a Fatal Error involving the OPA output function.

What's wrong? Please be specific.

## To reproduce ##
Invoke-SCuBA -OPAPath "C:\Temp\ScubaGear\" -ProductNames aad -OutPath "C:\XX\"

## Expected behavior ##
Expected a report

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

The script fails with this error:
Fatal Error involving the OPA output function.
            Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter '
InputObject' because it is null.
At C:\Temp\ScubaGear\PowerShell\ScubaGear\Modules\Orchestrator.psm1:697 char:13
             throw $InvokeRegoErrorMessage
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : OperationStopped: (Fatal Error inv...use it is null.:String) [], RuntimeException
     FullyQualifiedErrorId : Fatal Error involving the OPA output function.
                Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter 'InputObject' because it is null.


It creates a ProviderSettingsExport.json as only output file,

**Comment by gdasher** [comment]
Are you able to run opa manually on the system, for example:

`./opa_windows_amd64.exe version`

or, if that succeeds:

`./opa_windows_amd64.exe eval data.aad.tests -i /path/to/ProviderSettingsExport.json -d /path/to/AADConfig.rego -d /path/to/Utils/AAD.rego -f values`

Sometimes there are controls on a machine that block execution of the opa process.  Other times the issue is that there is some nuance in the provider settings json that we haven't seen before that trips up OPA when it tries to run the rules.

**Comment by Rost9220** [comment]
Yes, the result is:
PS C:\temp\ScubaGear> ./opa_windows_amd64.exe version
Version: 0.61.0
Build Commit: ea7a3e13c8fdceadeb199904facb4990fcb010f8
Build Timestamp: 2024-01-25T13:06:02Z
Build Hostname: c86b8b609133
Go Version: go1.21.5
Platform: windows/amd64
WebAssembly: available

And Eval fails with:

11 errors occurred:
\Temp\ScubaGear\PowerShell\ScubaGear\Rego\AADConfig.rego:112: rego_type_error: undefined function data.utils.key.FilterArray
\Temp\ScubaGear\PowerShell\ScubaGear\Rego\AADConfig.rego:126: rego_type_error: undefined function data.utils.report.NotCheckedDetails
\Temp\ScubaGear\PowerShell\ScubaGear\Rego\AADConfig.rego:165: rego_type_error: undefined function data.utils.key.FilterArray
\Temp\ScubaGear\PowerShell\ScubaGear\Rego\AADConfig.rego:215: rego_type_error: undefined function data.utils.key.Count
\Temp\ScubaGear\PowerShell\ScubaGear\Rego\AADConfig.rego:271: rego_type_error: undefined function data.utils.report.NotCheckedDetails
\Temp\ScubaGear\PowerShell\ScubaGear\Rego\AADConfig.rego:289: rego_type_error: undefined function data.utils.report.ReportDetailsBoolean
\Temp\ScubaGear\PowerShell\ScubaGear\Rego\AADConfig.rego:308: rego_type_error: undefined function data.utils.report.NotCheckedDetails
\Temp\ScubaGear\PowerShell\ScubaGear\Rego\AADConfig.rego:325: rego_type_error: undefined function data.utils.key.ConvertToSetWithKey
\Temp\ScubaGear\PowerShell\ScubaGear\Rego\AADConfig.rego:328: rego_type_error: undefined function data.utils.key.ConvertToSet
\Temp\ScubaGear\PowerShell\ScubaGear\Rego\AADConfig.rego:332: rego_type_error: undefined function data.utils.key.ConvertToSet
rego_compile_error: error limit reached

**Comment by concernednetizen** [comment]
Had same error message as OP, only for -ProductNames defender ... this happened when running the Invoke-Scuba command without -ProductNames, then when running individually it failed out only on defender. OPA process ran fine for all other ProductNames.

**Comment by concernednetizen** [comment]
We are running v. 1.1.1 , additionally we are getting the message before the error "unable to parse input: yaml: line 164: found unknown escape character just prior to the Fatal Error.

**Comment by gdasher** [comment]
Can you share around (+/- 3 lines) that line (164) of ProviderSettingsExport.json ?  Or any other line that shows up as invalid in VS Code to @buidav buidav point.

**Comment by concernednetizen** [comment]
looks like it is hitting the "Identity": "FFO.extest.microsoft.com/Microsoft Exchange Hosted Organizations/XXXX.onmicrosoft.com/Configuration/Custom - DLPPolicy - Ex\OD\SPO" ... the \O and \S are being read as escape characters, possibly due to our naming scheme on our policies. Did the same for the ld line below that.

**Comment by gdasher** [comment]
Thanks, that helps.  we'll look to reproduce and fix in an upcoming release.

**Comment by tkol2022** [comment]
@adhilto should we rename this issue to "OPA output function fails due to escape sequence" to make it easier to find in the future?

**Comment by reevesjeremy** [comment]
This causes the issue by replacing a properly escaped character set `\\/` leaving an unescaped character `\` from the DLP names that contain a forward slash. The affected properties are both Identity and Id.
https://github.com/cisagov/ScubaGear/blob/e57086431b40806f2a52c97f38a5cd03b1851315/PowerShell/ScubaGear/Modules/Orchestrator.psm1#L615-L616

Being more specific to target the Date solves this issue for me.
`$BaselineSettingsExport = $BaselineSettingsExport.replace("""\/Date(", """Date(").replace(")\/""",")""")`

I went heavy handed on the targeting, to include capturing the double quote, but it may not be necessary and could probably get by with this. You decide.
`$BaselineSettingsExport = $BaselineSettingsExport.replace("\/Date(", "Date(").replace(")\/",")")`

**Comment by tkol2022** [comment]
> This causes the issue by replacing a properly escaped character set `\\/` leaving an unescaped character `\` from the DLP names that contain a forward slash. The affected properties are both Identity and Id.
> 
> https://github.com/cisagov/ScubaGear/blob/e57086431b40806f2a52c97f38a5cd03b1851315/PowerShell/ScubaGear/Modules/Orchestrator.psm1#L615-L616
> 
> Being more specific to target the Date solves this issue for me. `$BaselineSettingsExport = $BaselineSettingsExport.replace("""\/Date(", """Date(").replace(")\/""",")""")`
> 
> I went heavy handed on the targeting, to include capturing the double quote, but it may not be necessary and could probably get by with this. You decide. `$BaselineSettingsExport = $BaselineSettingsExport.replace("\/Date(", "Date(").replace(")\/",")")`

thanks a lot for following up to help us.

**Comment by moneymoe23** [comment]
I have a similar issue while running the script. Would someone be kind enough to assist me with this error msg?

C:\Users\XXXXX\ScubaGear-1.1.1\PowerShell\ScubaGear\Modules\Providers\ProviderHelpers\SPOSiteHelper.psm1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r
unable to parse input: yaml: line 23243: found unknown escape character
unable to parse input: yaml: line 23243: found unknown escape character
unable to parse input: yaml: line 23243: found unknown escape character
unable to parse input: yaml: line 23243: found unknown escape character
unable to parse input: yaml: line 23243: found unknown escape character
Fatal Error involving the OPA output function.
            Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parameter
'InputObject' because it is null.
At C:\Users\XXXXX\ScubaGear-1.1.1\PowerShell\ScubaGear\Modules\Orchestrator.psm1:697 char:13
+             throw $InvokeRegoErrorMessage
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Fatal Error inv...use it is null.:String) [], RuntimeException
    + FullyQualifiedErrorId : Fatal Error involving the OPA output function.
                Ending ScubaGear execution. See the exception message for more details: Cannot bind argument to parame
   ter 'InputObject' because it is null.
   
   

![Screenshot 2024-04-25 125707](https://github.com/cisagov/ScubaGear/assets/167918184/c7d0eef5-79dd-42e6-8a39-6d09af30f93c)

**Comment by reevesjeremy** [comment]
> Would someone be kind enough to assist me with this error msg?

Modify the script as mentioned above and try it again. https://github.com/cisagov/ScubaGear/issues/935#issuecomment-2018372852

**Comment by moneymoe23** [comment]
Thanks @reevesjeremy, appreciate your help! it worked for me
