### ISSUE TITLE
Explore options for improving the readme

### ISSUE THREAD

**Issue by james-garriss** [cisagov/ScubaGear#941]
# 💡 Summary #

What is the work, as a high-level summary?

The current readme is long and intimidating for new users to read through.  The purpose of this issue is explore various options for representing this documentation in a format that is easier to read and understand.  Options include:

- Default Markdown
- Readthedocs
- GitHub Pages
- GitHub wiki

Once the options have been evaluated and pros/cons have been provided, the team can decide which approach to take.

## Motivation and context ##

This would be useful because when people can easily understand our documentation, they are more likely to use ScubaGear and use it without errors.

## Implementation notes ##

A plan for completion:

- Find all options
- Read docs for each
- Create list of pros/cons
- Present to team

## Acceptance criteria ##

How do we know when this work is done?

- [ ] When the team has sufficient information to make a choice.

**Comment by hapklaar** [comment]
Not sure if this is the right place to add to this, but one of the best additions or change to the doc, in my opinion, would be to specify exactly for each entry what the requirements are. For most this seems to be present in the form of implementation instructions, but not for everything. For example MS.AAD.1.1v1 fails for us, while we do have such a policy in place. The doc does not specify the exact requirements for this item, making it difficult to correct.

**Comment by tkol2022** [comment]
@hapklaar Thanks a lot for your feedback. It helps us improve the tool. Here is some information that can hopefully help you determine why AAD 1.1 is failing for you.

- The AAD 1.1 policy check is looking to see if your CA policy exactly matches the configuration [described by Microsoft on this page](https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-policy-block-legacy#create-a-conditional-access-policy) (however it must be turned On - not in Report-Only mode).
- Are you excluding any users or groups from the policy? If yes, then by default the policy will fail and you will need to setup [exemptions via a ScubaGear config file](https://github.com/cisagov/ScubaGear?tab=readme-ov-file#aad-conditional-access-policy-exemptions).

Please check your configuration against the one above and if you still have questions let me know.


Here are some potential ways we can improve the tool to be more clear about what the requirements for each policy evaluation are. Let me know what you think about each of these?

- Put a note at the top of each report that explains where the parameters for each policy evaluation come from. The tool checks the tenant configuration to ensure that it aligns with the parameter values documented in the baseline policy implementation instructions section.
- For AAD 1.1 (and potentially other policies), in the baseline document, we can expand the implementation instructions so that they explicitly describe the parameter configuration that the tool evaluates against. For AAD 1.1 we could add a conditional access policy configuration template similar to the one we have for AAD 2.1 in the screenshot below:

![image](https://github.com/cisagov/ScubaGear/assets/107076927/79efedf8-a7b9-405f-b26f-bf140b35d1fa)

**Comment by mitchelbaker-cisa** [comment]
As pointed out by @james-garriss https://github.com/cisagov/ScubaGear/issues/592 really should be included as its own markdown documentation. I only just uncovered that closed issue today, and Ted has a ton of useful information outlined.

**Comment by hapklaar** [comment]
@tkol2022 thanks. I have excluded our BTG account as recommended by MS in the article:
_- Under Exclude, select Users and groups and choose any accounts that must maintain the ability to use legacy authentication. Microsoft recommends you exclude at least one account to prevent yourself from being locked out._

The options you mention to clarify policy evaluation look like a welcome addition to me, especially details about policy evaluation. 

Going to check out the exemption option you mentioned!

**Comment by james-garriss** [comment]
After researching each of the 4 options above, listing the PROS and CONS, and presenting the results to Addam, we agreed that GitHub Pages is most likely the optimal choice.  It allows the README to remain with the code when packaged, and it provides an attractive, public-facing set of docs.  (Note that #877 will break the README into pieces and hopefully make the docs even better.). For now, this issues is completed.  If for any reason Pages does not work out as well as we expect, we can reopen this issue and look at other choices.
