### ISSUE TITLE
Investigate use of Code Signing Certificate

### ISSUE THREAD

**Issue by schrolla** [cisagov/ScubaGear#95]
Investigate how to sign w/ the right cert, etc.

**Comment by gdasher** [comment]
I took a look at this and did some prototyping in a fork of the repo here (so that I could create releases, etc): 

https://github.com/cisagov/ScubaGear/compare/main...gdasher:ScubaGear:main

This is using a self-signed cert.  @ethanb-cisa if you can upload the real cert as two secrets in the way the tools expect it:

1) Base64 encoded version of a .pfx file (PKCS#12 bundle of key and cert)
2) Secret with the password to that file

Then we can probably fairly easily incorporate this.  I am happy to own the implementation once the key and cert are uploaded in the appropriate format.

**Comment by ethanb-cisa** [comment]
Both are uploaded with pfx (key and cert) in base64.

**Comment by gdasher** [comment]
PR was put together in #120.  Basic testing was done to establish that it creates a viable release artifact that runs without unblock-file on LAN-A
